apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: vote
spec:
  type: ClusterIp
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    matchLabels:
      name: db-deployment
      app: demo-voting-app
