apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
  labels:
    name: redis-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deployment
      app: demo-voting-app
  template:
    metadata:
      name: redis-deployment
      labels:
        name: redis-deployment
        app: demo-voting-app
    spec:
      containers:
      - name: redis-deployment
        image: redis:alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      
      volumes:
      - name: redis-data
        emptyDir: {}
        

