apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
  labels:
    name: result-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-deployment
      app: demo-voting-app
  template:
    metadata:
      name: result-deployment
      labels:
        name: result-deployment
        app: demo-voting-app
    spec:
      containers:
      - name: result-deployment
        image: kodekloud/examplevotingapp_result:before
        ports:
        - containerPort: 80
